#!/usr/bin/env python3
"""Generate Figure 3 dose-response curves for all cancers.

Uses sweep_fold*.pkl generated by `audit-dct-reg sweep`. Schema:
    {alphas, risks_low (n_cases, n_alphas), risks_high (n_cases, n_alphas), dose}
"""
from __future__ import annotations

import argparse
import json
import os
import pickle
import subprocess
import sys
from pathlib import Path
from typing import Dict, List

import numpy as np

REPO_ROOT = Path("/data1/DCT-Reg")
OUTPUT_DIR = REPO_ROOT / "paper_outputs"

CANCERS = ["blca", "hnsc", "skcm", "lusc", "kirc", "brca", "coadread", "luad", "stad", "ucec"]
RESULT_BASE = REPO_ROOT / "results" / "dct_v3.10" / "robust" / "final_50ep_old"

CKPT_PATHS: Dict[str, Dict[int, str]] = {}
for cancer in CANCERS:
    base = RESULT_BASE / cancer / cancer / "SurvOTRank_dct_v310_directional_regularized_transport"
    if not base.exists():
        continue
    matching = list(base.glob(f"*dct_reg_{cancer}*"))
    if not matching:
        continue
    exp_dir = matching[0]
    for fold in range(5):
        ckpt = exp_dir / f"model_best_s{fold}.pth"
        if ckpt.exists():
            CKPT_PATHS.setdefault(cancer, {})[fold] = str(ckpt)

DEFAULT_ALPHAS = "0.0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0"


def run_sweep_for_cancer(cancer: str, gpu: int = 0, n_folds: int = 5) -> List[Path]:
    cfg = REPO_ROOT / "configs" / "dct_v310_directional_regularized_transport.yaml"
    audit_dir = REPO_ROOT / "results" / f"audit_{cancer}"
    audit_dir.mkdir(exist_ok=True)

    sweep_files = []
    for fold in range(n_folds):
        out_dir = audit_dir / cancer / f"fold_{fold}"
        out_dir.mkdir(parents=True, exist_ok=True)
        sweep_path = out_dir / f"sweep_fold{fold}.pkl"
        if sweep_path.exists():
            # Validate it has the new schema
            try:
                with open(sweep_path, "rb") as f:
                    d = pickle.load(f)
                if "risks_low" in d and "risks_high" in d:
                    sweep_files.append(sweep_path)
                    print(f"  ✓ {cancer.upper()} fold {fold}: sweep exists (new schema)")
                    continue
            except Exception:
                pass
            # old schema or corrupt → re-run
            sweep_path.unlink(missing_ok=True)

        ckpt = CKPT_PATHS.get(cancer, {}).get(fold)
        if not ckpt:
            print(f"  ⚠ {cancer.upper()} fold {fold}: no checkpoint")
            continue

        cmd = [
            "python3", str(REPO_ROOT / "scripts" / "audit_dct_reg.py"), "sweep",
            "--config", str(cfg),
            "--checkpoint", ckpt,
            "--fold", str(fold),
            "--alphas", DEFAULT_ALPHAS,
            "--output-dir", str(out_dir),
            "--gpu", str(gpu),
            "--set", f"study={cancer}",
        ]
        print(f"  Running: {cancer.upper()} fold {fold} sweep")
        try:
            r = subprocess.run(cmd, capture_output=True, text=True, timeout=600, cwd=REPO_ROOT)
            if r.returncode == 0 and sweep_path.exists():
                print(f"  ✓ {cancer.upper()} fold {fold}: sweep done")
                sweep_files.append(sweep_path)
            else:
                print(f"  ✗ {cancer.upper()} fold {fold}: failed (rc={r.returncode})")
                if r.stderr:
                    print(f"     {r.stderr[-300:]}")
        except subprocess.TimeoutExpired:
            print(f"  ✗ {cancer.upper()} fold {fold}: timeout")
        except Exception as e:
            print(f"  ✗ {cancer.upper()} fold {fold}: {e}")
    return sweep_files


def load_sweep(path: Path):
    with open(path, "rb") as f:
        d = pickle.load(f)
    return (np.array(d["alphas"]),
            np.array(d.get("risks_low", d.get("risks", np.empty((0, 0))))),
            np.array(d.get("risks_high", d.get("risks", np.empty((0, 0))))),
            d.get("dose", {}))


def aggregate_sweeps(sweep_files: List[Path]):
    alphas_list, low_list, high_list = [], [], []
    n_cases_total = 0
    for sf in sweep_files:
        a, low, high, _ = load_sweep(sf)
        if low.size == 0 or high.size == 0:
            continue
        alphas_list.append(a)
        # mean over patients per fold
        low_list.append(low.mean(axis=0))
        high_list.append(high.mean(axis=0))
        n_cases_total += low.shape[0]
    if not alphas_list:
        return None
    alphas = alphas_list[0]
    low_arr = np.stack(low_list)
    high_arr = np.stack(high_list)
    return {
        "alphas": alphas,
        "low_mean": low_arr.mean(axis=0),
        "low_sem": low_arr.std(axis=0) / np.sqrt(len(low_arr)),
        "high_mean": high_arr.mean(axis=0),
        "high_sem": high_arr.std(axis=0) / np.sqrt(len(high_arr)),
        "n_folds": len(low_list),
        "n_cases": n_cases_total // len(low_list),
    }


def make_dose_response_plot(per_cancer_data: Dict[str, Dict], output_path: Path):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    n = len(per_cancer_data)
    cols = min(n, 5)
    rows = (n + cols - 1) // cols
    fig, axes = plt.subplots(2 * rows, cols, figsize=(3.3 * cols, 3.3 * 2 * rows),
                             sharex=True, squeeze=False)

    for idx, (cancer, data) in enumerate(per_cancer_data.items()):
        r, c = divmod(idx, cols)
        alphas = data["alphas"]
        low_mean = data["low_mean"]
        low_sem = data["low_sem"]
        high_mean = data["high_mean"]
        high_sem = data["high_sem"]

        # Panel (a): absolute risk
        ax = axes[2 * r, c]
        ax.plot(alphas, low_mean, "b-o", lw=1.5, ms=4, label="Low-risk anchor")
        ax.fill_between(alphas, low_mean - low_sem, low_mean + low_sem, alpha=0.2, color="blue")
        ax.plot(alphas, high_mean, "r-s", lw=1.5, ms=4, label="High-risk anchor")
        ax.fill_between(alphas, high_mean - high_sem, high_mean + high_sem, alpha=0.2, color="red")
        ax.set_title(f"{cancer.upper()} (n={data['n_cases']}, {data['n_folds']} folds)",
                     fontsize=10, fontweight="bold")
        if c == 0:
            ax.set_ylabel("Predicted risk", fontsize=9)
        ax.legend(fontsize=7, loc="best")
        ax.grid(True, alpha=0.3)
        ax.set_xlim(-0.05, 1.05)

        # Panel (b): delta
        ax = axes[2 * r + 1, c]
        low_delta = low_mean - low_mean[0]
        high_delta = high_mean - high_mean[0]
        ax.plot(alphas, low_delta, "b-o", lw=1.5, ms=4, label="Low")
        ax.fill_between(alphas, low_delta - low_sem, low_delta + low_sem, alpha=0.2, color="blue")
        ax.plot(alphas, high_delta, "r-s", lw=1.5, ms=4, label="High")
        ax.fill_between(alphas, high_delta - high_sem, high_delta + high_sem, alpha=0.2, color="red")
        ax.axhline(0, color="gray", ls="--", alpha=0.5)
        ax.set_xlabel("Intervention strength α", fontsize=9)
        if c == 0:
            ax.set_ylabel("Δ Risk from baseline", fontsize=9)
        ax.legend(fontsize=7, loc="best")
        ax.grid(True, alpha=0.3)
        ax.set_xlim(-0.05, 1.05)

    # Hide unused axes
    total_axes = 2 * rows * cols
    used = 2 * len(per_cancer_data)
    for j in range(used, total_axes):
        r, c = divmod(j, cols)
        axes[r, c].axis("off")

    fig.suptitle("Figure 3: Counterfactual Dose-Response Curves (per-cancer)",
                 fontsize=13, fontweight="bold", y=1.00)
    fig.text(0.5, -0.01,
             "Mean ± SEM across folds. Predicted risk as intervention strength α → low (blue) or high (red) anchor.",
             ha="center", fontsize=8, style="italic")
    plt.tight_layout()
    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  ✓ Saved: {output_path}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--cancer", default="all")
    parser.add_argument("--gpu", type=int, default=0)
    parser.add_argument("--folds", default="0,1,2,3,4")
    parser.add_argument("--output", default=str(OUTPUT_DIR / "figure3_dose_response_all_cancers.png"))
    args = parser.parse_args()

    OUTPUT_DIR.mkdir(exist_ok=True)
    folds = [int(x) for x in args.folds.split(",")]

    cancers = [c.strip() for c in args.cancer.split(",")] if args.cancer != "all" else CANCERS
    per_cancer_data = {}

    for cancer in cancers:
        print(f"\n=== {cancer.upper()} ===")
        if cancer not in CKPT_PATHS or not CKPT_PATHS[cancer]:
            print(f"  ⚠ no checkpoints for {cancer}")
            continue
        sweep_files = run_sweep_for_cancer(cancer, gpu=args.gpu,
                                           n_folds=max(folds) + 1)
        if not sweep_files:
            print(f"  ⚠ no sweeps generated for {cancer}")
            continue
        agg = aggregate_sweeps(sweep_files)
        if agg:
            per_cancer_data[cancer] = agg
            print(f"  ✓ aggregated {agg['n_folds']} folds, {agg['n_cases']} cases")

    if not per_cancer_data:
        print("No data; aborting.")
        return

    out_path = Path(args.output)
    make_dose_response_plot(per_cancer_data, out_path)

    json_path = out_path.with_suffix(".json")
    serializable = {c: {k: (v.tolist() if hasattr(v, "tolist") else v)
                        for k, v in d.items()}
                    for c, d in per_cancer_data.items()}
    with open(json_path, "w") as f:
        json.dump(serializable, f, indent=2, default=float)
    print(f"  ✓ Saved data: {json_path}")


if __name__ == "__main__":
    main()